name: Update LeetCode Stats in README

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Count solved problems
        id: counts
        run: |
          count_dir() {
            dir="$1"
            if [ -d "$dir" ]; then
              find "$dir" -type f ! -path "*/.git/*" | wc -l
            else
              echo 0
            fi
          }

          EASY=$(count_dir "Easy")
          MEDIUM=$(count_dir "Medium")
          HARD=$(count_dir "Hard")
          TOTAL=$((EASY + MEDIUM + HARD))

          echo "EASY=$EASY" >> $GITHUB_ENV
          echo "MEDIUM=$MEDIUM" >> $GITHUB_ENV
          echo "HARD=$HARD" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV

          echo "Counts -> Easy:$EASY Medium:$MEDIUM Hard:$HARD Total:$TOTAL"

      - name: Update README
        run: |
          sed -i -E "s/^- Easy:.*/- Easy: ${EASY}/" README.md
          sed -i -E "s/^- Medium:.*/- Medium: ${MEDIUM}/" README.md
          sed -i -E "s/^- Hard:.*/- Hard: ${HARD}/" README.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README.md
          if git diff --staged --quiet; then
            echo "No README changes to commit"
          else
            git commit -m "Updating LeetCode counts (Easy:${EASY} Medium:${MEDIUM} Hard:${HARD})"
            git push
          fi
